from __future__ import annotations

from typing import Protocol

from backend.app.domain import Credential, CredentialKind, CredentialStatus


class CredentialStore(Protocol):
    async def get(self, kind: CredentialKind) -> Credential | None: ...
    async def is_configured(self, kind: CredentialKind) -> bool: ...
    async def key_tail(self, kind: CredentialKind) -> str | None: ...
    async def status(self, kind: CredentialKind) -> CredentialStatus: ...
    async def update(self, kind: CredentialKind, submitted_value: str) -> CredentialStatus: ...
    async def clear(self, kind: CredentialKind) -> CredentialStatus: ...
